### PR TITLE
Follow suit of urllib3 and drop python2.6

### PR DESCRIPTION
**Pull request by asottile**
- Already untested (?)
- Resolves https://github.com/urllib3/urllib3/issues/1456

I used [pyupgrade](https://github.com/asottile/pyupgrade) for the syntax changes.  Most of the motivation was to resolve the urllib3 issue.

### CODE REVIEW

**Comment by nateprewitt** [comment]
Hi @asottile, thanks for the pull request. As we noted in the urllib3 issue, this is already addressed and will be in our release within the next week once the changes in urllib3 have had some time to air out.

**Comment by nateprewitt** [comment]
I’ve created #4830 for visibility. Thanks again @asottile!

**Comment by asottile** [comment]
@nateprewitt disregarding the urllib3 issue -- is this PR not ok? does requests intend to support python2.6 (it doesn't test against it)

**Comment by nateprewitt** [comment]
There’s nothing wrong with the PR, but we already did this work a year ago. We haven’t supported python2.6 in a while but hadn’t intended to forcibly break compat until 3.0.0. 

The reason we declined to merge this is it’s more work to rebase the release commits and would remove credit from the original author. It also introduces some breakages that will affect a number of our downstream dependencies which are unrelated to 2.6.

**Pull request closed without merging**
