### PR TITLE
Removed legacy fallback for python3.2

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Windows Jenkins builder appears to be offline, blocking CI.

**Comment by nateprewitt** [comment]
@alex, would you mind rebasing this on the current master branch?

**Comment by alex** [comment]
@nateprewitt merged master in, looks green still

**Comment by nateprewitt** [comment]
Alright, I'm happy with this. Thanks @alex! ✨

**Pull request merged**
