### PR TITLE
for RFC-7616 add SHA-256 and SHA-512

### PR DESCRIPTION
**Pull request by linuxlizard**
While working with some FIPS libraries that disabled MD5, we ran into a problem with our Requests based tools not being able to talk to our server. 

screen shot 2017-11-08 at 4 19 47 pm

I haven't fully read the RFC-7616 SHA-256 and SHA-512 standards but this patch works.

Thanks for Requests!

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Could you add test cases for this, please?

**Comment by linuxlizard** [comment]
Can do.

**Comment by linuxlizard** [comment]
Status: I'm reaching out to Requests developers listed in "contributing" for some assistance adding tests.

**Comment by linuxlizard** [comment]
Status update: Twitter reply from @lukasaoz 
"  | Lukasaoz @linuxlizard I doubt httpbin supports these auth modes yet so you may need to begin by adding support there. Alternatively you can use code like test_lowlevel.py to force the correct responses.Nov 14, 2017, 12:01 PM
-- | --

I'm going to investigate that approach.

**Comment by linuxlizard** [comment]
Status update: Twitter reply from @lukasaoz 
"  | Lukasaoz @linuxlizard I doubt httpbin supports these auth modes yet so you may need to begin by adding support there. Alternatively you can use code like test_lowlevel.py to force the correct responses.Nov 14, 2017, 12:01 PM
-- | --

I'm going to investigate that approach.

**Comment by linuxlizard** [comment]
Created pull request for httpbin to add SHA-512 support.
https://github.com/kennethreitz/httpbin/pull/401

**Comment by linuxlizard** [comment]
Thanksgiving over. httpbin patch accepted. Back to work on learning how to add tests to Requests.

**Comment by linuxlizard** [comment]
Shutting down this pull request. Creating a new pull request with test code.

**Pull request closed without merging**
