### PR TITLE
info for #4259 DO NOT MERGE

### PR DESCRIPTION
**Pull request by ofek**

### CODE REVIEW

**Comment by ofek** [comment]
@kennethreitz Hey there! Could you please re-open this? There is a hanging test I want to verify in CI.

**Comment by kennethreitz** [comment]
sorry!

**Comment by ofek** [comment]
@kennethreitz No problem! I submitted #4259

**Comment by Lukasa** [comment]
Ok, so the first note is that I don't reproduce this failure locally. That suggests that the failure is environmental: either OS-based (I'm on macOS) or something more nuanced. My first guess is that it's related to proxies, so I'm going to chase that rabbit hole.

**Comment by Lukasa** [comment]
Ok if we fail out of the `mixed_case_scheme_acceptable` test the next test hangs instead. Let me see if I can escape that one too.

**Comment by Lukasa** [comment]
Ok so what seems to be happening is that the HTTP server is blocking forever. Let's try to find out why.

**Comment by Lukasa** [comment]
Hrm, here's a weirdness: this doesn't appear to happen when I run the tests under tox.

**Comment by Lukasa** [comment]
Ohhhhh I know what this will be. Ok, one sec.

**Comment by Lukasa** [comment]
Yup, got it. Ok, will open a PR that fixes this problem.

**Comment by ofek** [comment]
Between this and that macOS memory allocation thing, you're the King of Bug Hunting!

**Comment by Lukasa** [comment]
Heh, thanks!

**Pull request closed without merging**
