### PR TITLE
New HTTPHeaderDict class for response headers with multiple header value support

### PR DESCRIPTION
**Pull request by the-allanc**
Same changes as my other pull request #4282, but this against the proposed/3.0.0 branch.

### CODE REVIEW

**Comment by the-allanc** [comment]
The CI builds are failing on tests which were failing before my changes were pushed (honest!)

**Comment by kennethreitz** [comment]
We know :)

@Lukasa what do you think of this? I'm very :+1: personally.

**Comment by kennethreitz** [comment]
I think this will be a major improvement to Requests.

**Comment by ml31415** [comment]
Why reinventing the wheel? `urllib3` has a multiheader-ready headers implementation for ages. Stable, fast, reviewed and well tested. If I remember correctly, it was already suggested a while ago to reuse it also in requests, so that it could be avoided to copy and re-read all the headers, which would also be a considerable speed improvement on creating a Response object.

**Comment by kennethreitz** [comment]
Merged into '3.0' branch. ✨🍰✨

**Comment by kennethreitz** [comment]
Pending further modifications.

**Pull request closed without merging**
