### PR TITLE
Add long_description_content_type to setup.py

### PR DESCRIPTION
**Pull request by pradyunsg**
See:
- https://packaging.python.org/guides/making-a-pypi-friendly-readme/
- https://pypi.org/p/requests/

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Duplicate of #4623

**Comment by pradyunsg** [comment]
Oh. Wait, it should be `text/x-rst`. Do you want me to open a new PR?

**Comment by kennethreitz** [comment]
Or update this one!

**Comment by sigmavirus24** [comment]
My understanding was that if the readme is in RST, this isn't necessary to specify. Did the PEP change?

**Comment by kennethreitz** [comment]
I think it's nice-to-have.

**Comment by kennethreitz** [comment]
I'll certianly reference it a lot, and it'll be educational for our users.

**Comment by pradyunsg** [comment]
@sigmavirus24 if you'd reopen, I'll make the change. :)

**Comment by sigmavirus24** [comment]
:crossed_fingers: this starts a new build on Travis

**Pull request merged**
