### PR TITLE
Avoid importing platform

### PR DESCRIPTION
**Pull request by methane**
platform module is relatively large: it takes about 5ms to import.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Is `sys.platform` always equal to `win32` even on 64bit windows installations?

**Comment by sethmlarson** [comment]
Might wanna do `sys.platform.startswith('win')`? I've seen that in another library, can't recall which.

**Comment by methane** [comment]
It is always 'win32'.
https://docs.python.org/3/library/sys.html#sys.platform

https://github.com/python/cpython/blob/d6bb65f378e34fe0c11fdb39588357ecf22964eb/PC/pyconfig.h#L297-L301

**Comment by sigmavirus24** [comment]
Once https://github.com/kennethreitz/httpbin/pull/392 merges and Kevin releases a pytest-httpbin package, the tests here should start passing.

**Comment by nateprewitt** [comment]
@methane would you mind rebasing this onto the current master branch?

**Comment by methane** [comment]
done

**Comment by sethmlarson** [comment]
:tada: LGTM

**Pull request merged**
