### PR TITLE
update json param's description to avoid confusion

### PR DESCRIPTION
**Pull request by Obeyed**
- the Request class doesn't accept JSON, but a JSON serializable object

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Closing and re-opening to trigger a rebuild on AppVeyor

**Comment by nateprewitt** [comment]
Actually, @Obeyed would you mind rebasing this onto the current master branch?

**Comment by Obeyed** [comment]
Done! :+1:

**Comment by nateprewitt** [comment]
Since we don't need to worry about the tests with this change, I'm going to merge so it doesn't get out of sync again. Thanks again for contributing to Requests, @Obeyed!

**Pull request merged**
