### PR TITLE
Added type hints for help.py.

### PR DESCRIPTION
**Pull request by RatanShreshtha**
This my first PR to this project please review and give feedback to me how can I improve.

### CODE REVIEW

**Comment by kennethreitz** [comment]
Is Dict proper here, or MutableMapping? Learning myself :)

**Comment by kennethreitz** [comment]
Actually, let's have this import from `requests.types`

**Comment by kennethreitz** [comment]
@RatanShreshtha made some changes, please review for future PRs :)

**Comment by RatanShreshtha** [comment]
thanks, @kennethreitz  so for future I should use the types .py?

**Comment by kennethreitz** [comment]
@RatanShreshtha correct!

**Pull request merged**
