### PR TITLE
Revert "Convert version compatibility checks to warnings"

### PR DESCRIPTION
**Pull request by kennethreitz**
Reverts requests/requests#4144

### CODE REVIEW

**Comment by kennethreitz** [comment]
continuation of https://github.com/requests/requests/pull/4144#issuecomment-307426091

**Comment by kennethreitz** [comment]
restarting for windows

**Comment by sigmavirus24** [comment]
So we definitely don't want a complete revert of this. I do think we we want a selective revert though. We absolutely want to be more resilient to versions we can't parse. I don't think we want to emit warnings though.

**Comment by kennethreitz** [comment]
windows passed!

**Comment by nateprewitt** [comment]
Alright, I'd like to wrap this up so these commits aren't stuck in limbo. @sigmavirus24, my take away from the discussion is you'd still like to see exceptions over the warnings but allow for more resilient checks. What do you see happening when we can't parse a dependency? Is that still an exception with the unparsed version included in the message? How would we allow something like `python-telegram-bot` to work if they force a vendored copy of urllib3 onto the path?

You also said you'd rather not use `assert` statements to the `python -O` concerns. I'm assuming you'd rather see this as a conditional check that raises the exception?

If that all sounds correct, and @Lukasa/@kennethreitz are on board, I'll put the follow-up together.

**Comment by sigmavirus24** [comment]
> How would we allow something like python-telegram-bot to work if they force a vendored copy of urllib3 onto the path?

Briefly responding to one question here: The point is to not allow that. I have to wonder if the exception shouldn't also include the location to the module so people can see "Hey, telegram bot is doing something real stupid and it's breaking requests."

**Comment by mongarneb** [comment]
Hola estamos en un curso

**Comment by mongarneb** [comment]
Hola estamos en un curso

**Pull request closed without merging**
