### PR TITLE
add missing packages when parse document

### PR DESCRIPTION
**Pull request by wangwenpei**

### CODE REVIEW

**Comment by Lukasa** [comment]
Thanks for this! However, there is no need for it: when you install the Requests package by pip or setup.py those packages will be installed for you.

**Comment by 9nix00** [comment]
Ah, I see. it looks my requests version is too old. I use `requests==2.13.0`.

maybe we should add some note in document to notice user ?

**Comment by Lukasa** [comment]
What would that look like?

**Comment by 9nix00** [comment]
I think maybe we can add it in [release-and-version-history](http://docs.python-requests.org/en/master/community/updates/#release-and-version-history) ?

parse document should be no error. if user didn't install `requests` and they just need document. 
they should know which package depends on. I still think a better way is to create a `requirements.txt` for document. this is a normal way.e.g:[scrapy](https://github.com/scrapy/scrapy/tree/master/docs)

of course, different community,different rule. respect community leaders choice.

**Comment by Lukasa** [comment]
It is considered a bad idea to create `requirements.txt` for this. `requirements.txt` is really considered to be used only for a *specific installation*, not for a general statement of what is needed. `setup.py` is pretty much the standard way to do this.

If you want to build the docs then you *have* to install Requests, as we use Sphinx autodoc to build our API documentation, and that only works if you've installed the package.

**Pull request closed without merging**
