### PR TITLE
standard library suppress instead of try...except...pass

### PR DESCRIPTION
**Pull request by Hyaxia**
Code readability :)
Just thought it would be nice to use the suppress instead of the except...pass usage.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
I'm -1ish on this change because it seems to purely be a refactoring that isn't necessary which can make archaeology on bugs significantly more difficult. I'm not a fan of change for change's sake when it comes to requests.

**Comment by nateprewitt** [comment]
I think I’m in agreement with @sigmavirus24 here. While this does make a small simplification to the code it’s adding additional overhead to ensure we continue using this going forward.

I think we’ll pass on this change for now, @hyaxia, but thank you for putting the idea forward!

**Comment by Hyaxia** [comment]
Thanks for replying.
@nateprewitt, Just out of curiousity, if there was no need for the python 2.7 compatibility, and you could use the "suppress" method from the standard library,
(There was no need for the function i created but just to import the class from contextlib)
 would your opinion on the matter be different?

**Comment by nateprewitt** [comment]
We’ve discussed removing Python 2 support as part of Requests 3.0 but I don’t know if that decision has been finalized. We may revisit this at that point but until then I think we’re unlikely to merge a change like this.

**Comment by Hyaxia** [comment]
Cool thanks!

**Pull request closed without merging**
