### PR TITLE
Type annoted requests/__init__.py.

### PR DESCRIPTION
**Pull request by RatanShreshtha**

### CODE REVIEW

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by RatanShreshtha** [comment]
@kennethreitz  Shouldn't there be a step listing to run mypy before submitting the contribution for 3.0 as other things are listed in http://docs.python-requests.org/en/master/dev/contributing/#steps-for-submitting-code?

**Comment by kennethreitz** [comment]
one thing at a time.

**Comment by kennethreitz** [comment]
i'm planning on doing most of the type annotations myself

**Pull request merged**
