### PR TITLE
Simple fix for the issue #2392

### PR DESCRIPTION
**Pull request by VasiliPupkin256**
The issue also has duplicates  #2620 and my recent #4467

### CODE REVIEW

**Comment by sigmavirus24** [comment]
Sadly we can't just accept an API breaking change without documentation that it happened in the release notes. Please write something up for the change log.

**Comment by VasiliPupkin256** [comment]
We have already discussed this bug yesterday and I commit it to the 3.0.0 branch, how those release notes should look like?

**Comment by nateprewitt** [comment]
@VasiliPupkin256 can you please add an entry to `3.0-History.rst` to the effect of:

"Exception raised during read timeout for `iter_content` and `iter_lines` changed from `ConnectionError` to more specific `ReadTimeout`."

**Comment by VasiliPupkin256** [comment]
@nateprewitt done

**Comment by nateprewitt** [comment]
Thanks @VasiliPupkin256! ✨

**Pull request merged**
